export type TranslatorLanguage = string;

export const translatorLanguages: Record<TranslatorLanguage, { name: string; flag: string; nativeName: string }> = {
  af: { name: 'Afrikaans', flag: '🇿🇦', nativeName: 'Afrikaans' },
  sq: { name: 'Albanian', flag: '🇦🇱', nativeName: 'Shqip' },
  am: { name: 'Amharic', flag: '🇪🇹', nativeName: 'አማርኛ' },
  ar: { name: 'Arabic', flag: '🇸🇦', nativeName: 'العربية' },
  hy: { name: 'Armenian', flag: '🇦🇲', nativeName: 'Հայերեն' },
  az: { name: 'Azerbaijani', flag: '🇦🇿', nativeName: 'Azərbaycan' },
  eu: { name: 'Basque', flag: '🇪🇸', nativeName: 'Euskara' },
  be: { name: 'Belarusian', flag: '🇧🇾', nativeName: 'Беларуская' },
  bn: { name: 'Bengali', flag: '🇧🇩', nativeName: 'বাংলা' },
  bs: { name: 'Bosnian', flag: '🇧🇦', nativeName: 'Bosanski' },
  bg: { name: 'Bulgarian', flag: '🇧🇬', nativeName: 'Български' },
  ca: { name: 'Catalan', flag: '🇪🇸', nativeName: 'Català' },
  zh: { name: 'Chinese', flag: '🇨🇳', nativeName: '中文' },
  hr: { name: 'Croatian', flag: '🇭🇷', nativeName: 'Hrvatski' },
  cs: { name: 'Czech', flag: '🇨🇿', nativeName: 'Čeština' },
  da: { name: 'Danish', flag: '🇩🇰', nativeName: 'Dansk' },
  nl: { name: 'Dutch', flag: '🇳🇱', nativeName: 'Nederlands' },
  en: { name: 'English', flag: '🇬🇧', nativeName: 'English' },
  et: { name: 'Estonian', flag: '🇪🇪', nativeName: 'Eesti' },
  fi: { name: 'Finnish', flag: '🇫🇮', nativeName: 'Suomi' },
  fr: { name: 'French', flag: '🇫🇷', nativeName: 'Français' },
  gl: { name: 'Galician', flag: '🇪🇸', nativeName: 'Galego' },
  ka: { name: 'Georgian', flag: '🇬🇪', nativeName: 'ქართული' },
  de: { name: 'German', flag: '🇩🇪', nativeName: 'Deutsch' },
  el: { name: 'Greek', flag: '🇬🇷', nativeName: 'Ελληνικά' },
  gu: { name: 'Gujarati', flag: '🇮🇳', nativeName: 'ગુજરાતી' },
  ht: { name: 'Haitian Creole', flag: '🇭🇹', nativeName: 'Kreyòl ayisyen' },
  he: { name: 'Hebrew', flag: '🇮🇱', nativeName: 'עברית' },
  hi: { name: 'Hindi', flag: '🇮🇳', nativeName: 'हिन्दी' },
  hu: { name: 'Hungarian', flag: '🇭🇺', nativeName: 'Magyar' },
  is: { name: 'Icelandic', flag: '🇮🇸', nativeName: 'Íslenska' },
  id: { name: 'Indonesian', flag: '🇮🇩', nativeName: 'Bahasa Indonesia' },
  ga: { name: 'Irish', flag: '🇮🇪', nativeName: 'Gaeilge' },
  it: { name: 'Italian', flag: '🇮🇹', nativeName: 'Italiano' },
  ja: { name: 'Japanese', flag: '🇯🇵', nativeName: '日本語' },
  kn: { name: 'Kannada', flag: '🇮🇳', nativeName: 'ಕನ್ನಡ' },
  kk: { name: 'Kazakh', flag: '🇰🇿', nativeName: 'Қазақ' },
  ko: { name: 'Korean', flag: '🇰🇷', nativeName: '한국어' },
  lv: { name: 'Latvian', flag: '🇱🇻', nativeName: 'Latviešu' },
  lt: { name: 'Lithuanian', flag: '🇱🇹', nativeName: 'Lietuvių' },
  mk: { name: 'Macedonian', flag: '🇲🇰', nativeName: 'Македонски' },
  ms: { name: 'Malay', flag: '🇲🇾', nativeName: 'Bahasa Melayu' },
  mt: { name: 'Maltese', flag: '🇲🇹', nativeName: 'Malti' },
  mr: { name: 'Marathi', flag: '🇮🇳', nativeName: 'मराठी' },
  mn: { name: 'Mongolian', flag: '🇲🇳', nativeName: 'Монгол' },
  ne: { name: 'Nepali', flag: '🇳🇵', nativeName: 'नेपाली' },
  no: { name: 'Norwegian', flag: '🇳🇴', nativeName: 'Norsk' },
  fa: { name: 'Persian', flag: '🇮🇷', nativeName: 'فارسی' },
  pl: { name: 'Polish', flag: '🇵🇱', nativeName: 'Polski' },
  pt: { name: 'Portuguese', flag: '🇵🇹', nativeName: 'Português' },
  pa: { name: 'Punjabi', flag: '🇮🇳', nativeName: 'ਪੰਜਾਬੀ' },
  ro: { name: 'Romanian', flag: '🇷🇴', nativeName: 'Română' },
  ru: { name: 'Russian', flag: '🇷🇺', nativeName: 'Русский' },
  sr: { name: 'Serbian', flag: '🇷🇸', nativeName: 'Српски' },
  sk: { name: 'Slovak', flag: '🇸🇰', nativeName: 'Slovenčina' },
  sl: { name: 'Slovenian', flag: '🇸🇮', nativeName: 'Slovenščina' },
  es: { name: 'Spanish', flag: '🇪🇸', nativeName: 'Español' },
  sw: { name: 'Swahili', flag: '🇰🇪', nativeName: 'Kiswahili' },
  sv: { name: 'Swedish', flag: '🇸🇪', nativeName: 'Svenska' },
  tl: { name: 'Tagalog', flag: '🇵🇭', nativeName: 'Tagalog' },
  ta: { name: 'Tamil', flag: '🇮🇳', nativeName: 'தமிழ்' },
  te: { name: 'Telugu', flag: '🇮🇳', nativeName: 'తెలుగు' },
  th: { name: 'Thai', flag: '🇹🇭', nativeName: 'ไทย' },
  tr: { name: 'Turkish', flag: '🇹🇷', nativeName: 'Türkçe' },
  uk: { name: 'Ukrainian', flag: '🇺🇦', nativeName: 'Українська' },
  ur: { name: 'Urdu', flag: '🇵🇰', nativeName: 'اردو' },
  uz: { name: 'Uzbek', flag: '🇺🇿', nativeName: 'O\'zbek' },
  vi: { name: 'Vietnamese', flag: '🇻🇳', nativeName: 'Tiếng Việt' },
  cy: { name: 'Welsh', flag: '🏴󐁧󐁢󐁷󐁬󐁳󐁿', nativeName: 'Cymraeg' }
};

export const getPopularLanguages = (): TranslatorLanguage[] => {
  return ['en', 'ru', 'es', 'fr', 'de', 'zh', 'ja', 'ko', 'ar', 'pt', 'it', 'hi'];
};
